In [ ]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 20.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 21.5 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
import numpy as np
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from google.colab import drive
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

# Load the CSV file with robust handling
try:
    df = pd.read_csv(
        '/content/drive/My Drive/output.csv',  # Path to the file
        on_bad_lines='skip',  # Skip problematic rows
        escapechar="\\",      # Handle escape characters
        encoding='utf-8',     # Ensure UTF-8 encoding
        engine='python'       # Use Python engine for better error handling
    )
    print("CSV file loaded successfully!")
except Exception as e:
    print(f"Error loading CSV file: {e}")

# Display the first few rows to verify
# df.head()

CSV file loaded successfully!


In [ ]:
df.head()

topic            source  bias  \
0   politics          Politico     0   
1      china         Bloomberg     1   
2  terrorism  Washington Times     2   
3   politics             Salon     0   
4   politics    CNN (Web News)     0   

                                                 url  \
0  https://www.politico.com/news/magazine/2019/11...   
1  https://www.bloomberg.com/news/articles/2018-0...   
2  http://www.washingtontimes.com/news/2014/sep/1...   
3  http://www.salon.com/2014/11/12/americas_post_...   
4  http://www.cnn.com/2014/01/08/politics/christi...   

                                               title        date  \
0  Can the Impeachment Hearings Actually Change A...  2019-11-13   
1  Trump’s Tariff Barrage Pushes China Fight to P...  2018-07-11   
2  Top general: Failed Foley rescue was ‘highest-...  2014-09-16   
3  America’s post-midterm inferno: Tea Party garb...  2014-11-12   
4  E-mails among Christie appointees suggest poli...  2014-01-08   

                      authors  \
0                         NaN   
1  Brendan Scott, Enda Curran   
2               Stephen Dinan   
3             Robert Hennelly   
4       Catherine E. Shoichet   

                                             content  \
0  This happens for different reasons , but a key...   
1  LISTEN TO ARTICLE 5:37 SHARE THIS ARTICLE Shar...   
2  The Pentagon ’ s top general said Tuesday that...   
3  A full week after the alleged “ shellacking “ ...   
4  Story highlights Gergen : `` It feeds into thi...   

                                    content_original               source_url  \
0  This happens for different reasons, but a key ...         www.politico.com   
1  LISTEN TO ARTICLE 5:37 SHARE THIS ARTICLE Shar...        www.bloomberg.com   
2  The Pentagon’s top general said Tuesday that t...  www.washingtontimes.com   
3  A full week after the alleged “shellacking “ o...            www.salon.com   
4  Story highlights Gergen: "It feeds into this n...              www.cnn.com   

  bias_text                ID  
0      left  bpp2Cqpvyi2ER5Lr  
1    center  PnVV1v7F0D8bhd5X  
2     right  pZlutCuZNm832qqK  
3      left  aMGkvFlpLyQrX6iu  
4      left  Ludq48gCzDiKtnmX

In [ ]:

df = df.drop(columns=['source_url', 'url','content_original','authors'])

In [ ]:
df

topic            source  bias  \
0         politics          Politico     0   
1            china         Bloomberg     1   
2        terrorism  Washington Times     2   
3         politics             Salon     0   
4         politics    CNN (Web News)     0   
...            ...               ...   ...   
37549   media_bias          Fox News     2   
37550    education               Vox     0   
37551    elections          The Hill     1   
37552    education            Reason     2   
37553  us_congress   Fox Online News     2   

                                                   title        date  \
0      Can the Impeachment Hearings Actually Change A...  2019-11-13   
1      Trump’s Tariff Barrage Pushes China Fight to P...  2018-07-11   
2      Top general: Failed Foley rescue was ‘highest-...  2014-09-16   
3      America’s post-midterm inferno: Tea Party garb...  2014-11-12   
4      E-mails among Christie appointees suggest poli...  2014-01-08   
...                                                  ...         ...   
37549  Summit meeting: Can there be a 'reset' between...  2016-11-22   
37550  All of West Virginia’s teachers have been on s...  2018-03-03   
37551  Kirsten Gillibrand officially announces White ...  2019-03-17   
37552  Why We Need School Choice: "Obama Administrati...  2017-01-23   
37553  McConnell rails against Mueller report politic...         NaN   

                                                 content bias_text  \
0      This happens for different reasons , but a key...      left   
1      LISTEN TO ARTICLE 5:37 SHARE THIS ARTICLE Shar...    center   
2      The Pentagon ’ s top general said Tuesday that...     right   
3      A full week after the alleged “ shellacking “ ...      left   
4      Story highlights Gergen : `` It feeds into thi...      left   
...                                                  ...       ...   
37549  If Donald Trump can sit down with Mitt Romney ...     right   
37550  Thousands of public school teachers across Wes...      left   
37551  Sen. Kirsten Gillibrand Kirsten GillibrandTo w...    center   
37552  Welcome to National School Choice Week , an an...     right   
37553  Senate Majority Leader Mitch McConnell , in a ...     right   

                     ID  
0      bpp2Cqpvyi2ER5Lr  
1      PnVV1v7F0D8bhd5X  
2      pZlutCuZNm832qqK  
3      aMGkvFlpLyQrX6iu  
4      Ludq48gCzDiKtnmX  
...                 ...  
37549  aDXaucBITOvKX6Sl  
37550  78Akx2nSokxbCMd0  
37551  vvAgpKy0PL1h8990  
37552  aWlri1iRio9Q6Rfe  
37553  3BMrcnVjf3C8Rsgz  

[37554 rows x 8 columns]

In [ ]:
# Combine 'title' and 'content' as input text
df['text'] = df['title'] + " " + df['content']

In [ ]:
df

topic            source  bias  \
0         politics          Politico     0   
1            china         Bloomberg     1   
2        terrorism  Washington Times     2   
3         politics             Salon     0   
4         politics    CNN (Web News)     0   
...            ...               ...   ...   
37549   media_bias          Fox News     2   
37550    education               Vox     0   
37551    elections          The Hill     1   
37552    education            Reason     2   
37553  us_congress   Fox Online News     2   

                                                   title        date  \
0      Can the Impeachment Hearings Actually Change A...  2019-11-13   
1      Trump’s Tariff Barrage Pushes China Fight to P...  2018-07-11   
2      Top general: Failed Foley rescue was ‘highest-...  2014-09-16   
3      America’s post-midterm inferno: Tea Party garb...  2014-11-12   
4      E-mails among Christie appointees suggest poli...  2014-01-08   
...                                                  ...         ...   
37549  Summit meeting: Can there be a 'reset' between...  2016-11-22   
37550  All of West Virginia’s teachers have been on s...  2018-03-03   
37551  Kirsten Gillibrand officially announces White ...  2019-03-17   
37552  Why We Need School Choice: "Obama Administrati...  2017-01-23   
37553  McConnell rails against Mueller report politic...         NaN   

                                                 content bias_text  \
0      This happens for different reasons , but a key...      left   
1      LISTEN TO ARTICLE 5:37 SHARE THIS ARTICLE Shar...    center   
2      The Pentagon ’ s top general said Tuesday that...     right   
3      A full week after the alleged “ shellacking “ ...      left   
4      Story highlights Gergen : `` It feeds into thi...      left   
...                                                  ...       ...   
37549  If Donald Trump can sit down with Mitt Romney ...     right   
37550  Thousands of public school teachers across Wes...      left   
37551  Sen. Kirsten Gillibrand Kirsten GillibrandTo w...    center   
37552  Welcome to National School Choice Week , an an...     right   
37553  Senate Majority Leader Mitch McConnell , in a ...     right   

                     ID                                               text  
0      bpp2Cqpvyi2ER5Lr  Can the Impeachment Hearings Actually Change A...  
1      PnVV1v7F0D8bhd5X  Trump’s Tariff Barrage Pushes China Fight to P...  
2      pZlutCuZNm832qqK  Top general: Failed Foley rescue was ‘highest-...  
3      aMGkvFlpLyQrX6iu  America’s post-midterm inferno: Tea Party garb...  
4      Ludq48gCzDiKtnmX  E-mails among Christie appointees suggest poli...  
...                 ...                                                ...  
37549  aDXaucBITOvKX6Sl  Summit meeting: Can there be a 'reset' between...  
37550  78Akx2nSokxbCMd0  All of West Virginia’s teachers have been on s...  
37551  vvAgpKy0PL1h8990  Kirsten Gillibrand officially announces White ...  
37552  aWlri1iRio9Q6Rfe  Why We Need School Choice: "Obama Administrati...  
37553  3BMrcnVjf3C8Rsgz  McConnell rails against Mueller report politic...  

[37554 rows x 9 columns]

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

# Split data into features and labels
X = df['text']  # Assuming your text column is named 'text'
y = df['bias']  # Assuming your labels column is named 'label'

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# TF-IDF vectorization
tfidf = TfidfVectorizer(ngram_range=(1, 2), max_features=5000)  # Unigrams and bigrams, limit features to 5000
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train Multinomial Naive Bayes
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

# Evaluate on test set
y_pred = nb.predict(X_test_tfidf)
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))




Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.60      0.59      2601
           1       0.59      0.51      0.55      2163
           2       0.60      0.65      0.63      2747

    accuracy                           0.59      7511
   macro avg       0.59      0.59      0.59      7511
weighted avg       0.59      0.59      0.59      7511

Confusion Matrix:
[[1551  371  679]
 [ 562 1105  496]
 [ 562  387 1798]]


In [ ]:
# Save TF-IDF vectorizer and model for reuse
import joblib
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(nb, 'naive_bayes_model.pkl')

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split data into features and labels
X = df['text']  # Assuming your text column is named 'text'
y = df['bias']  # Assuming your labels column is named 'label'

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# TF-IDF vectorization
tfidf = TfidfVectorizer(ngram_range=(1, 2), max_features=5000)  # Unigrams and bigrams, limit features to 5000
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train Multinomial Naive Bayes
nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

# Evaluate on test set
y_pred = nb.predict(X_test_tfidf)

# Overall metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')  # 'weighted' handles class imbalance
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

print("Overall Metrics:")
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)



Overall Metrics:
Accuracy: 0.59
Precision: 0.59
Recall: 0.59
F1-Score: 0.59

Confusion Matrix:
[[1551  371  679]
 [ 562 1105  496]
 [ 562  387 1798]]


In [ ]:

# Save TF-IDF vectorizer and model for reuse
import joblib
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(nb, 'naive_bayes_model.pkl')